excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://akkomar.github.io
title: Arkadiusz Komarzewski
tagline: Software, JVM, Scala, Cassandra
description: My awesome new site
paginate: 10